### ISSUE TITLE
License and crediting question

### ISSUE THREAD

**Issue by miguelpaz** [advanced-js/syllabus#70]
I don't teach a JS course, however I loved the course structure. If I fork and reuse any part of it, which attribution, license and link back should I add?

**Comment by ceefour** [comment]
I love it too! :) https://struktur-data.github.io/syllabus/ 

As mentioned in [course website](https://advanced-js.github.io/syllabus/), it would be Creative Commons Attribution 4.0 International License.

BTW since there's no Sharealike, that means your modified work can be in any license as long as it attributes @afeld's work :)

**Comment by afeld** [comment]
Indeed! Sorry for not responding sooner.
